/*
 * Copyright 2026 RethinkDNS and its authors
 */
package com.bernaferrari.bravedns.di

import com.bernaferrari.bravedns.ui.compose.about.AppMetadata
import com.bernaferrari.bravedns.ui.compose.about.RethinkWebDemoMetadata
import org.koin.core.annotation.Configuration
import org.koin.core.annotation.ComponentScan
import org.koin.core.annotation.KoinApplication
import org.koin.core.annotation.Module
import org.koin.core.annotation.Single

/**
 * Values consumed by the target-neutral Compose demo.
 *
 * The browser gets these through the generated Koin graph rather than reaching into Android
 * package metadata. Android retains its real metadata provider in the application graph.
 */
data class RethinkWebDemoDependencies(
    val appMetadata: AppMetadata,
)

/** Compiler-backed definitions that are valid on every shared target. */
@Module
class RethinkWebDemoModule {
    @Single
    fun demoDependencies(): RethinkWebDemoDependencies =
        RethinkWebDemoDependencies(appMetadata = RethinkWebDemoMetadata)
}

/**
 * Root shared Koin configuration, generated by the Koin compiler plugin.
 *
 * Platform-only bindings remain in their respective source sets. The Android application uses
 * its own generated root, which includes this common configuration at compile time.
 */
@Module(includes = [RethinkWebDemoModule::class])
@Configuration
@ComponentScan("com.bernaferrari.bravedns.viewmodel")
class RethinkSharedModule

@KoinApplication(modules = [RethinkSharedModule::class])
object RethinkKoinApp
