package com.bernaferrari.bravedns.ui.icons

import androidx.compose.ui.graphics.vector.ImageVector

/**
 * Material Symbols Rounded vectors generated by scripts/generate-material-symbols.sh.
 *
 * Filled and Outlined map to the Material Symbols FILL axis. AutoMirrored marks directional
 * usages at the call site while retaining an ImageVector-compatible API for common UI.
 */
object MaterialSymbols {
    object Filled {
        val Add: ImageVector get() = filledAdd
        val Apps: ImageVector get() = filledApps
        val Article: ImageVector get() = filledArticle
        val ArrowBack: ImageVector get() = filledArrowBack
        val ArrowForward: ImageVector get() = filledArrowForward
        val AutoStories: ImageVector get() = filledAutoStories
        val Backup: ImageVector get() = filledBackup
        val BarChart: ImageVector get() = filledBarChart
        val Block: ImageVector get() = filledBlock
        val BrightnessAuto: ImageVector get() = filledBrightnessAuto
        val BugReport: ImageVector get() = filledBugReport
        val Build: ImageVector get() = filledBuild
        val BusinessCenter: ImageVector get() = filledBusinessCenter
        val CalendarMonth: ImageVector get() = filledCalendarMonth
        val CameraAlt: ImageVector get() = filledCameraAlt
        val Cancel: ImageVector get() = filledCancel
        val CellTower: ImageVector get() = filledCellTower
        val Chat: ImageVector get() = filledChat
        val ChatBubble: ImageVector get() = filledChatBubble
        val Check: ImageVector get() = filledCheck
        val CheckCircle: ImageVector get() = filledCheckCircle
        val Clear: ImageVector get() = filledClear
        val Close: ImageVector get() = filledClose
        val Cloud: ImageVector get() = filledCloud
        val Code: ImageVector get() = filledCode
        val ContentCopy: ImageVector get() = filledContentCopy
        val DarkMode: ImageVector get() = filledDarkMode
        val Delete: ImageVector get() = filledDelete
        val DeleteOutline: ImageVector get() = filledDeleteOutline
        val Dns: ImageVector get() = filledDns
        val Download: ImageVector get() = filledDownload
        val Edit: ImageVector get() = filledEdit
        val EditLocationAlt: ImageVector get() = filledEditLocationAlt
        val Email: ImageVector get() = filledEmail
        val EventNote: ImageVector get() = filledEventNote
        val FilterList: ImageVector get() = filledFilterList
        val Forum: ImageVector get() = filledForum
        val Gavel: ImageVector get() = filledGavel
        val GppBad: ImageVector get() = filledGppBad
        val Group: ImageVector get() = filledGroup
        val Headset: ImageVector get() = filledHeadset
        val HelpOutline: ImageVector get() = filledHelpOutline
        val Home: ImageVector get() = filledHome
        val Http: ImageVector get() = filledHttp
        val Info: ImageVector get() = filledInfo
        val KeyboardArrowDown: ImageVector get() = filledKeyboardArrowDown
        val KeyboardArrowRight: ImageVector get() = filledKeyboardArrowRight
        val Language: ImageVector get() = filledLanguage
        val LightMode: ImageVector get() = filledLightMode
        val LocalTaxi: ImageVector get() = filledLocalTaxi
        val Lock: ImageVector get() = filledLock
        val Map: ImageVector get() = filledMap
        val MobileOff: ImageVector get() = filledMobileOff
        val MobiledataArrows: ImageVector get() = filledMobiledataArrows
        val MobiledataOff: ImageVector get() = filledMobiledataOff
        val MoreHoriz: ImageVector get() = filledMoreHoriz
        val MoreVert: ImageVector get() = filledMoreVert
        val Movie: ImageVector get() = filledMovie
        val MusicNote: ImageVector get() = filledMusicNote
        val NetworkCheck: ImageVector get() = filledNetworkCheck
        val NetworkPing: ImageVector get() = filledNetworkPing
        val NewReleases: ImageVector get() = filledNewReleases
        val Notifications: ImageVector get() = filledNotifications
        val NotificationsOff: ImageVector get() = filledNotificationsOff
        val Palette: ImageVector get() = filledPalette
        val PhoneAndroid: ImageVector get() = filledPhoneAndroid
        val PhotoLibrary: ImageVector get() = filledPhotoLibrary
        val PlayArrow: ImageVector get() = filledPlayArrow
        val Policy: ImageVector get() = filledPolicy
        val Public: ImageVector get() = filledPublic
        val RadioButtonChecked: ImageVector get() = filledRadioButtonChecked
        val RadioButtonUnchecked: ImageVector get() = filledRadioButtonUnchecked
        val Refresh: ImageVector get() = filledRefresh
        val Remove: ImageVector get() = filledRemove
        val RestartAlt: ImageVector get() = filledRestartAlt
        val Restore: ImageVector get() = filledRestore
        val Search: ImageVector get() = filledSearch
        val Security: ImageVector get() = filledSecurity
        val Send: ImageVector get() = filledSend
        val Settings: ImageVector get() = filledSettings
        val Share: ImageVector get() = filledShare
        val Shield: ImageVector get() = filledShield
        val ShieldMoon: ImageVector get() = filledShieldMoon
        val Shop: ImageVector get() = filledShop
        val ShoppingCart: ImageVector get() = filledShoppingCart
        val SignalCellularAlt: ImageVector get() = filledSignalCellularAlt
        val Star: ImageVector get() = filledStar
        val StarBorder: ImageVector get() = filledStarBorder
        val Stop: ImageVector get() = filledStop
        val Storage: ImageVector get() = filledStorage
        val Subject: ImageVector get() = filledSubject
        val SystemUpdate: ImageVector get() = filledSystemUpdate
        val SystemUpdateAlt: ImageVector get() = filledSystemUpdateAlt
        val Timer: ImageVector get() = filledTimer
        val Tune: ImageVector get() = filledTune
        val VpnKey: ImageVector get() = filledVpnKey
        val Warning: ImageVector get() = filledWarning
        val WarningAmber: ImageVector get() = filledWarningAmber
        val WbSunny: ImageVector get() = filledWbSunny
        val Wifi: ImageVector get() = filledWifi
        val WifiOff: ImageVector get() = filledWifiOff
        val Work: ImageVector get() = filledWork
    }

    object Outlined {
        val Home: ImageVector get() = outlinedHome
        val Info: ImageVector get() = outlinedInfo
        val Settings: ImageVector get() = outlinedSettings
        val Star: ImageVector get() = outlinedStar
        val StarBorder: ImageVector get() = outlinedStarBorder
        val MobiledataArrows: ImageVector get() = outlinedMobiledataArrows
        val MobiledataOff: ImageVector get() = outlinedMobiledataOff
    }

    object AutoMirrored {
        object Filled {
            val ArrowBack: ImageVector get() = filledArrowBack
            val ArrowForward: ImageVector get() = filledArrowForward
            val Article: ImageVector get() = filledArticle
            val Chat: ImageVector get() = filledChat
            val HelpOutline: ImageVector get() = filledHelpOutline
            val KeyboardArrowRight: ImageVector get() = filledKeyboardArrowRight
            val Send: ImageVector get() = filledSend
            val Subject: ImageVector get() = filledSubject
        }
    }
}
