package com.celzero.bravedns.ui.compose.theme

import androidx.compose.ui.graphics.Color

// Light palette
val PrimaryLight = Color(0xFF804136)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFFFDBD3)
val OnPrimaryContainerLight = Color(0xFF32120C)
val SecondaryLight = Color(0xFF755A54)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFFFDBD3)
val OnSecondaryContainerLight = Color(0xFF2B1612)
val TertiaryLight = Color(0xFF6F5D2E)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFF9E1A6)
val OnTertiaryContainerLight = Color(0xFF251A00)
val BackgroundLight = Color(0xFFFFF8F6)
val OnBackgroundLight = Color(0xFF231A18)
val SurfaceLight = Color(0xFFFFF8F6)
val OnSurfaceLight = Color(0xFF231A18)
val SurfaceVariantLight = Color(0xFFF4DED9)
val OnSurfaceVariantLight = Color(0xFF54433F)
val OutlineLight = Color(0xFF86736E)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)

// Dark palette
val PrimaryDark = Color(0xFFFFB4A3)
val OnPrimaryDark = Color(0xFF4C1E15)
val PrimaryContainerDark = Color(0xFF653429)
val OnPrimaryContainerDark = Color(0xFFFFDBD3)
val SecondaryDark = Color(0xFFE6BDB4)
val OnSecondaryDark = Color(0xFF432A25)
val SecondaryContainerDark = Color(0xFF5C3F39)
val OnSecondaryContainerDark = Color(0xFFFFDBD3)
val TertiaryDark = Color(0xFFDBC58C)
val OnTertiaryDark = Color(0xFF3D2F05)
val TertiaryContainerDark = Color(0xFF554519)
val OnTertiaryContainerDark = Color(0xFFF9E1A6)
val BackgroundDark = Color(0xFF1A1110)
val OnBackgroundDark = Color(0xFFF0DEDA)
val SurfaceDark = Color(0xFF1A1110)
val OnSurfaceDark = Color(0xFFF0DEDA)
val SurfaceVariantDark = Color(0xFF53433F)
val OnSurfaceVariantDark = Color(0xFFD8C2BC)
val OutlineDark = Color(0xFFA08C87)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)

// True Black palette
val PrimaryBlack = Color(0xFFFFB7A7)
val OnPrimaryBlack = Color(0xFF45170F)
val PrimaryContainerBlack = Color(0xFF5F2E24)
val OnPrimaryContainerBlack = Color(0xFFFFDBD3)
val SecondaryBlack = Color(0xFFE8BDB2)
val OnSecondaryBlack = Color(0xFF3E2722)
val SecondaryContainerBlack = Color(0xFF583C36)
val OnSecondaryContainerBlack = Color(0xFFFFDBD3)
val TertiaryBlack = Color(0xFFDCC58B)
val OnTertiaryBlack = Color(0xFF3A2D03)
val TertiaryContainerBlack = Color(0xFF514214)
val OnTertiaryContainerBlack = Color(0xFFF9E1A6)
val BackgroundBlack = Color(0xFF090607)
val OnBackgroundBlack = Color(0xFFF0DEDA)
val SurfaceBlack = Color(0xFF090607)
val OnSurfaceBlack = Color(0xFFF0DEDA)
val SurfaceVariantBlack = Color(0xFF4F3F3B)
val OnSurfaceVariantBlack = Color(0xFFD6C1BC)
val OutlineBlack = Color(0xFF9E8B86)
val ErrorBlack = Color(0xFFFFB4AB)
val OnErrorBlack = Color(0xFF690005)
val ErrorContainerBlack = Color(0xFF93000A)
val OnErrorContainerBlack = Color(0xFFFFDAD6)

// Light Plus palette
val PrimaryLightPlus = Color(0xFF7C3F57)
val OnPrimaryLightPlus = Color(0xFFFFFFFF)
val PrimaryContainerLightPlus = Color(0xFFFFD9E4)
val OnPrimaryContainerLightPlus = Color(0xFF310F1D)
val SecondaryLightPlus = Color(0xFF6D5C66)
val OnSecondaryLightPlus = Color(0xFFFFFFFF)
val SecondaryContainerLightPlus = Color(0xFFF7DDEB)
val OnSecondaryContainerLightPlus = Color(0xFF251821)
val BackgroundLightPlus = Color(0xFFFFF7FB)
val OnBackgroundLightPlus = Color(0xFF201A1E)
val SurfaceLightPlus = Color(0xFFFFF7FB)
val OnSurfaceLightPlus = Color(0xFF201A1E)
val SurfaceVariantLightPlus = Color(0xFFF0DEE6)
val OnSurfaceVariantLightPlus = Color(0xFF51434A)
val OutlineLightPlus = Color(0xFF83737B)
val AccentGoodLightPlus = Color(0xFF006D43)
val AccentBadLightPlus = Color(0xFFBA1A1A)

// True Black Plus palette
val PrimaryBlackPlus = Color(0xFFFFB0CA)
val OnPrimaryBlackPlus = Color(0xFF4B142A)
val PrimaryContainerBlackPlus = Color(0xFF653041)
val OnPrimaryContainerBlackPlus = Color(0xFFFFD9E4)
val SecondaryBlackPlus = Color(0xFFE2C0CE)
val OnSecondaryBlackPlus = Color(0xFF422A34)
val SecondaryContainerBlackPlus = Color(0xFF5B3F49)
val OnSecondaryContainerBlackPlus = Color(0xFFFEDAE8)
val BackgroundBlackPlus = Color(0xFF0E090D)
val OnBackgroundBlackPlus = Color(0xFFEFDFE6)
val SurfaceBlackPlus = Color(0xFF0E090D)
val OnSurfaceBlackPlus = Color(0xFFEFDFE6)
val SurfaceVariantBlackPlus = Color(0xFF503F46)
val OnSurfaceVariantBlackPlus = Color(0xFFD5C2CA)
val OutlineBlackPlus = Color(0xFF9D8B92)
val AccentGoodBlackPlus = Color(0xFF6DF2B6)
val AccentBadBlackPlus = Color(0xFFFFB4AB)

val SeedColor = Color(0xFF804136)
